### ISSUE TITLE
Update docker hub links

### ISSUE THREAD

**Issue by ericis** [WeihanLi/docker-env#1]
Update any docker links intended for the community...

**From:**
https://cloud.docker.com/repository/docker/weihanli/puppeteer

**To:**
https://hub.docker.com/r/weihanli/puppeteer

**Comment by WeihanLi** [comment]
Thanks @ericis , I'll fix this laterly.

**Comment by ericis** [comment]
FYI: Personally using your docker image here: https://github.com/ourchitecture/site-ionic-ng/blob/9652e842d12d95c0099260c53a03ffa27b51c7fd/.cirrus.yml#L14

*Currently testing CI across Travis CI, Circle CI, and Cirrus CI (all working so far...)

Thanks for your work!

**Comment by WeihanLi** [comment]
Thanks, you could contact me whenever any problem met.
